# eds_extract.jl from ExtractCompress2.jl (home 30/7 4.34pm) [drive 29/7]
# edited 11/8

using NCDatasets, Dates

"""
    eds_extract(input_path::String, output_path::String, varnames::Vector{String};
					update_metadata=false)

Extracts multiple variables from `input_path` and saves them together into a single `output_path`.
Automatically generates and copies matching coordinate axes (like longitude, latitude, valid_time).
"""

# usage example:
# Call the function with an array of variables you wish to bundle together
#extract_and_compress_variables("input_file.nc", "output_bundle.nc", ["swir"])

function eds_extract(input::String, output::String, varnames::Vector{String};
						update_metadata=false)

    ds_in=NCDataset(input, "r")
    ds_out=NCDataset(output, "c", format=:netcdf4)
	try
            
        # STEP 1: Copy Global Attributes
        for (k, v) in ds_in.attrib
            ds_out.attrib[k] = v
        end
            
        var_list_str = join(varnames, ", ")

        # Master tracker to check what has ALREADY been written to ds_out
        processed_variables = Set{String}()

        
        # STEP 2: Process Each Target Variable
        
        for varname in varnames
            # Defensive check: if it was already generated by an axis lookup, skip to avoid Error -42
            if varname in processed_variables
                continue
            end

            if !haskey(ds_in, varname)
                @warn "Variable '$varname' not found in source file. Skipping."
                continue
            end
                
            v_src = ds_in[varname]
            v_type = eltype(v_src.var) 
            target_dims = dimnames(v_src)

            # --- 2A: Set up dimensions and coordinate variables ---
            for d_name in target_dims
                # 1. Define dimension if missing
                if !haskey(ds_out.dim, d_name)
                    dim_len = ds_in.dim[d_name]
                    defDim(ds_out, d_name, dim_len)
                end
                    
                # 2. Extract and create coordinate variables safely
                if haskey(ds_in, d_name) && !(d_name in processed_variables)
                    coord_src = ds_in[d_name]
                    coord_type = eltype(coord_src.var)
                    dim_len = ds_in.dim[d_name]
                        
                    # Flexible time catching for "valid_time", "time_bounds", etc.
                    if occursin("time", lowercase(d_name))
                        coord_chunks = [1] # Force isolate single slices
                    else
                        coord_chunks = [dim_len] # Full vector block chunk
                    end
                        
                    v_coord = defVar(ds_out, d_name, coord_type, (d_name,);
                                    attrib = coord_src.attrib,
                                    hunksizes = coord_chunks,
                                    deflatelevel = 1,
                                    shuffle = true)
                    v_coord[:] = coord_src[:]
                    push!(processed_variables, d_name)
                end
            end

            # --- 2B: Configure chunk sizes for the data grid ---
            c_sizes = Int[]
            for d_name in target_dims
                if occursin("time", lowercase(d_name))
                    push!(c_sizes, 1)
                else
                    push!(c_sizes, ds_in.dim[d_name]) 
                end
            end

            # --- 2C: Define and extract main variable data ---
            v_dst = defVar(ds_out, varname, v_type, target_dims; 
							attrib = v_src.attrib, 
                            chunksizes = c_sizes,
                            deflatelevel = 1,
                            shuffle = true)

            colons = tuple(fill(Colon(), length(target_dims))...)
            v_dst[colons...] = v_src[colons...]
                
            push!(processed_variables, varname)
            println(" -> Bundled and compressed variable: '$varname'")
        end
		if update_metadata
            ds_out.attrib["history"] = get(ds_in.attrib, "history", "") * 
                "\n[$(Dates.now())] Extracted variables [$var_list_str] and applied NetCDF4 compression."
		end
    finally
		close(ds_in)
		close(ds_out)

		return output
    end
end
